# coding=utf-8
"""
Django settings for Alex_shop project.

Generated by 'django-admin startproject' using Django 1.8.14.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'lxf4!vk_5hsqckc$)*pv-967+$(&wxc90q7)vz!dj9ds3m8&zc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

THUMBNAIL_DEBUG = True

ALLOWED_HOSTS = []

PORTAL_URL = 'http://127.0.0.1:8000'

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shop',
    'cart',
    'account',
    'sorl.thumbnail',
    'order',
    'paypal.standard.ipn',
    'weasyprint',
    'cupons',
)

AUTH_USER_MODEL = 'account.User'

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',

)

ROOT_URLCONF = 'Alex_shop.urls'

AUTHENTICATION_BACKENDS = (
    'account.backends.LoginUsingEmailAsUsernameBackend',
    'django.contrib.auth.backends.ModelBackend',
)

ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'email'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'Alex_shop.context_processors.shop_processors',
                'shop.context_processors.categories_processors',
                'cart.context_processors.cart',
                'account.context_processors.user_full_name',
                'cart.context_processors.wish_list',
            ],
        },
    },
]

WSGI_APPLICATION = 'Alex_shop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'alex_shop.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(os.path.expanduser('~'),
                           '/home/berluskuni/web_project/Alex_shop/static')
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'assets'),

)
STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
)

MEDIA_ROOT = os.path.join(BASE_DIR, "..", 'media')

MEDIA_URL = '/media/'

CART_SESSION_ID = 'cart'

DEFAULT_FROM_EMAIL = 'berluskuni@gmail.com'
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'berluskuni@gmail.com'
EMAIL_HOST_PASSWORD = 'ganzhik7897770'
EMAIL_PORT = 587

# Email
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Paypal

PAYPAL_RECEIVER_EMAIL = 'berluskuni@mail.ru'
PAYPAL_TEST = True



